### ISSUE TITLE
Expanded Functionality: Combine IDML Documents

### ISSUE THREAD

**Issue by sligh** [zandrmartin/php-idml#2]
I put together a proof of concept that populates IDML templates, with placeholder text, from a database. It then combines them by:

1. Appending the story and spread IDs with uniqid()
2. Performs a find/replace on the original IDs and unique IDs in the xml filenames and their contents.
3. Copies the first unzipped IDML to a new "combined" and loads all of the other IDML file stories into the "combined"
4. Appends the "combined" spread to include new idPkg:Spread elements for each of the new spreads.

This is an ugly method. I ran across your class and I think that your DOMDocument would be much cleaner. 

I am not very savvy with DOMDocuments but it appears that the following methods would be a very useful addition for simple combinations of relatively identical source documents:

*these make methods would make the IDs unique. For story, it would have to update the reference within its parent spread. They would also need to be updated in designmap.
makeSpreadIdsUnique()
makeSpreadIdUnique($spreadId)
makeStoryIdsUnique()
makeStoryIdUnique($storyId)

* These add methods would bring in spreads and stories from a separate instance of IDMLPackage.
addSpreads($spreads)
addStories($stories)
addSpreadsAndStories()

For example: $combinedIDMLDocument->addSpreadsAndStories($secondIDML)

What are your thoughts?

**Comment by zandrmartin** [comment]
Ok, I think I get what you're asking for here. Let me repeat it to see if we're on the same page. You have a single "template" IDML file. You make a copy of this template, modify both copies, and want to combine them back into a single IDML. But now you have two different versions of each story and spread, and each version has the same self attribute, so you have to modify that attribute and populate the new attribute through the entire package. Did I get that right?

Assuming I did, I think it would be relatively easy to implement. Based on a sample file I have available, an individual story's self attribute is used in (at least) four places:

1. the `Self` attribute of the `Story` element in the story itself
2. the `ParentStory` attribute of an individual element within another story or spread; in my sample this is a `TextFrame` element but it could also be a `Rectangle` or `XMLElement` or who knows what else
3. the `StoryList` attribute of the `Document` element in the design map
4. the filename of the story itself, generally `Story_<id>.xml`, which is referenced in the `src` attribute of `idPkg:Story` elements in the design map

Of course it would definitely be worth reviewing the IDML specification to verify where else a story's self attribute may be referenced. The four places listed above are easy enough to find and change; we know where 1, 3 and 4 are, and 2 can be found with a simple XPath query.

**Comment by sligh** [comment]
Those were the only uses/crossrefs that I found in my workflow. I thought that linked text frames generated some other cross references. However, I checked the spec/ran a test and it didn't generate additional cross references.

Would it make sense to add some error handling that looks at the different idmls to ensure that the only difference between them is in the designmap and spreads/stories folders?

**Comment by zandrmartin** [comment]
I started poking around with this and realized this is going to be trickier than expected. The main issue is the uniqueness of `Self` attributes. It's not just stories and spreads that have them - nearly every single element in every file has a `Self`, and as far as I know they all have to be globally unique. (One of the most annoying bugs I ever solved was a duplicated `Self` attribute that only occurred under very specific circumstances; it took hours to track down.)

Even if you ignore some of those `Self`s that are formatted differently (e.g. `Font` element `Self`s generally seem to look like `di2fcFontnFamily Weight Style`), `Layer`s, `TextFrame`s, `GraphicLine`s all have `Self`s that seem to follow the `u12a`-style formatting.

So, every spread or story you add to the package will need to have the `Self` attribute of every element it contains checked for uniqueness and changed if it conflicts. That change needs to be recursively propagated throughout every other place in the `$this` package AND in the package it's coming from - because if you change something in story A when you add it to `$this`, and later you add story B which has a reference to an element in story A, that reference needs to be intact.

These problems aren't necessarily unsolvable, but there a little more complex than I first guessed, so I'm going to have to rethink strategy here.

**Comment by sligh** [comment]
My workflows were for two identical IDML that only have modified stories with regard to text find/replace. So you make the spread and stories unique and then combine. I never considered further work on the instance after the combine. Good point.
